# fly.toml app configuration file generated for big-boi-agent on 2025-07-17T15:27:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-boi-agent'
primary_region = 'iad'

[build]

[env]

[[mounts]]
source = 'khoj_data'
destination = '/root/.khoj'

[http_service]
internal_port = 42110
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
interval = '30s'
timeout = '5s'
grace_period = '10s'
method = 'GET'
path = '/health'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
