flyctl secrets set POSTGRES_HOST=postgrdb.x.supabase.co \
    POSTGRES_DB=postgres \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=xxx \
    POSTGRES_PORT=5432 \
    KHOJ_DJANGO_SECRET_KEY=xxx \
    KHOJ_ADMIN_EMAIL=dat.b.do@gmail.com \
    KHOJ_ADMIN_PASSWORD=xxx \
    ANTHROPIC_API_KEY=sk-ant-xxx \
    SERPER_DEV_API_KEY=xx \
    OLOSTEP_API_KEY=xx \
    E2B_API_KEY=xx \
    KHOJ_DOMAIN=big-boi-agent.fly.dev \
    KHOJ_ALLOWED_DOMAIN=big-boi-agent.fly.dev \
    KHOJ_NO_HTTPS=False \
    KHOJ_TELEMETRY_DISABLE=True
