export const PHOTO_UPLOAD_PREFIX = "PHOTO_UPLOAD/";

export const POST_STATE = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
};

export default {
  POST_STATE,
  PHOTO_UPLOAD_PREFIX,
};
