enum PostStatus {
  DRAFT
  PUBLISHED
  ARCHIVED
}

type Post
  @model
  @auth(
    rules: [
      { allow: groups, provider: userPools, groups: ["BigBoiSuperAdmin"], operations: [read, create, update, delete] }
      { allow: owner, provider: userPools, operations: [read, create, update, delete] }
      { allow: private, provider: identityPool, operations: [read, create, update] }
      { allow: public, operations: [read] }
      { allow: public, provider: identityPool, operations: [read] }
    ]
  )
{
  id: ID!
  title: String!
  description: String
  status: PostStatus! @index(name: "byUpdatedAt", queryField: "PostByUpdatedAt", sortKeyFields: ["updatedAt"])
  tags: [String]
  data: AWSJSON!
  postType: String
  updatedAt: AWSDateTime!
  externalLink: String
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
  owner: String
}

type Comment
  @model
  @auth(
    rules: [
      { allow: groups, provider: userPools, groups: ["BigBoiSuperAdmin"], operations: [read, create, update, delete] }
      { allow: owner, provider: userPools, operations: [read, create, update, delete] }
      { allow: private, provider: identityPool, operations: [read, create, update, delete] }
      { allow: public, operations: [read] }
      { allow: public, provider: identityPool, operations: [read, create] }
    ]
  )
{
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post @belongsTo(fields: ["postID"])
  content: String!
  owner: String
}

type EventMessage
  @model
  @auth(
    rules: [
      { allow: groups, provider: userPools, groups: ["BigBoiSuperAdmin"], operations: [read, create, update, delete] }
      { allow: owner, provider: userPools, operations: [read, create, update, delete] }
      { allow: private, provider: identityPool, operations: [read, create, update] }
      { allow: public, operations: [read] }
      { allow: public, provider: identityPool, operations: [read] }
    ]
  )
{
  id: ID!
  type: String! @index(name: "byTimestamp", queryField: "EventMessageByTimestamp", sortKeyFields: ["timestamp"])
  sourceID: String!
  source: String!
  eventType: String!
  content: AWSJSON!
  metadata: AWSJSON!
  publishInfo: AWSJSON!
  timestamp: AWSDateTime!
}

type PrivateEventMessage
  @model
  @auth(
    rules: [
      { allow: groups, provider: userPools, groups: ["BigBoiSuperAdmin"], operations: [read, create, update, delete] }
      { allow: owner, provider: userPools, operations: [read, create, update, delete] }
      { allow: private, provider: identityPool, operations: [read, create, update] }
    ]
  )
{
  id: ID!
  type: String! @index(name: "byTimestamp", queryField: "PrivateEventMessageByTimestamp", sortKeyFields: ["timestamp"])
  sourceID: String!
  source: String!
  eventType: String!
  content: AWSJSON!
  metadata: AWSJSON!
  publishInfo: AWSJSON!
  timestamp: AWSDateTime!
}

type Reference
  @model
  @auth(
    rules: [
      { allow: groups, provider: userPools, groups: ["BigBoiSuperAdmin"], operations: [read, create, update, delete] }
      { allow: owner, provider: userPools, operations: [read, create, update, delete] }
      { allow: private, provider: identityPool, operations: [read, create, update] }
      { allow: public, operations: [read] }
      { allow: public, provider: identityPool, operations: [read] }
    ]
  )
{
  id: ID!
  title: String!
  url: String
  description: String
  extraData: AWSJSON
  type: String
    @index(name: "byUpdatedAt", queryField: "ReferenceByUpdatedAt", sortKeyFields: ["updatedAt"])
    @index(name: "byClickCount", queryField: "ReferenceByClickCount", sortKeyFields: ["clickCount"])
  clickCount: Int
  updatedAt: AWSDateTime!
  tags: [String]
}

type PrivateReference
  @model
  @auth(
    rules: [
      { allow: groups, provider: userPools, groups: ["BigBoiSuperAdmin"], operations: [read, create, update, delete] }
      { allow: owner, provider: userPools, operations: [read, create, update, delete] }
      { allow: private, provider: identityPool, operations: [read, create, update] }
    ]
  )
{
  id: ID!
  title: String!
  url: String
  description: String
  extraData: AWSJSON
  type: String
    @index(name: "byUpdatedAt", queryField: "PrivateReferenceByUpdatedAt", sortKeyFields: ["updatedAt"])
    @index(name: "byClickCount", queryField: "PrivateReferenceByClickCount", sortKeyFields: ["clickCount"])
  clickCount: Int
  updatedAt: AWSDateTime!
  tags: [String]
}
